package com.vendorflow.shared.persistence;

import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Transient;
import java.util.UUID;
import org.springframework.data.domain.Persistable;

/**
 * Base for entities whose UUID primary key is generated by the application (no sequential ids exposed).
 * Implements {@link Persistable} so Spring Data's save() issues a plain INSERT instead of a "select then merge"
 * for entities that already carry an id.
 */
@MappedSuperclass
public abstract class UuidEntity implements Persistable<UUID> {

    @Id
    private UUID id;

    @Transient
    private boolean isNew = true;

    protected UuidEntity() {
    }

    protected UuidEntity(UUID id) {
        this.id = id;
    }

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        this.isNew = false;
    }

    @Override
    public boolean equals(Object o) {
        return this == o || (o instanceof UuidEntity other && id != null && id.equals(other.id)
                && getClass().equals(other.getClass()));
    }

    @Override
    public int hashCode() {
        return id == null ? 0 : id.hashCode();
    }
}
